media: assets/img
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, date, categories, tags ]
      default:
        sort: date
        order: desc
    fields:
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: YYYY-MM-DDTHH:mm
      - name: title
        label: Title
        type: string
      - name: categories
        label: Categories
        type: string
        list: true
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: rich-text
  - name: about
    label: About page
    path: about.markdown
    type: file
    fields:
      - name: title
        label: Page title
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: YYYY-MM-DDTHH:mm
      - name: body
        label: Body
        type: rich-text
  - name: config
    label: Jekyll config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)