---
title: Jamie Lord
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:name"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: false
    share: false
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
- scope:
    path: _projects
    type: projects
  values:
    layout: single
    author_profile: true
subtitle: Lord.technology
logo: "/assets/images/JL_logo.png"
og_image: "/assets/images/JL_logo.png"
url: https://lord.technology
repository: jamie-lord/Lord.technology
email: jamie@lord.technology
description: Jamie Lord is Solution Architect at CDS, using Cloudflare, Azure
  and AWS to build awesome projects
github_username: jamie-lord
minimal_mistakes_skin: lord
search: true
locale: en-GB
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: "/:year/:month/:day/:title:output_ext"
paginate: 5
paginate_path: "/page:num/"
include:
- _pages
plugins:
- jekyll-remote-theme
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
- jekyll-seo-tag
author:
  name: Jamie Lord
  avatar: "/assets/images/jamie.jpg"
  bio: Solution Architect at CDS, using Azure and C# to build awesome projects
  location: Lincoln, UK
  links:
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/jamie-lord
  - label: LinkedIn
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/in/jamie-lord-3564472a4/
social:
  type: Person
  name: Jamie Lord
  links:
  - https://github.com/jamie-lord
footer:
  links:
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/jamie-lord
  - label: LinkedIn
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/in/jamie-lord-3564472a4/
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  comments: all
  blanklines: true
  ignore:
    envs: development
analytics:
  provider: google-gtag
  google:
    tracking_id: G-SV12MR8FCS
