title: Jamie Lord
subtitle: Lord.technology
name: Jamie Lord
email: jamie@lord.technology
url: https://lord.technology
description: >-
  Jamie Lord is a Solution Architect at CDS, building multi-tenant SaaS
  applications with C#, Cloudflare, Azure and AWS.
author:
  name: Jamie Lord
  role: Solution Architect
  location: Stamford, UK
  avatar: "/assets/images/jamie.jpg"
  url: https://lord.technology
  email: jamie@lord.technology
  github: jamie-lord
  linkedin: jamie-lord-3564472a4
logo: "/assets/images/JL_logo.png"
og_image: "/assets/images/JL_logo.png"
repository: jamie-lord/Lord.technology
github_username: jamie-lord
locale: en-GB
timezone: Europe/London
markdown: kramdown
permalink: "/:year/:month/:day/:title:output_ext"

collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:name"
  uploads:
    title: Uploads
    output: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: _pages
      type: pages
    values:
      layout: page
  - scope:
      path: _projects
      type: projects
    values:
      layout: page

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-gist
  - jekyll-redirect-from
  - jemoji

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  blanklines: true
  ignore:
    envs: development

analytics:
  provider: google-gtag
  google:
    tracking_id: G-SV12MR8FCS
