---
title: Jamie Lord - Lord.technology
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:name"
  uploads:
    title: Uploads
    output: true
header_title: Jamie Lord
author: Jamie Lord
email: jamie@lord.technology
description: Jamie Lord is a lead developer based in Nottingham, UK using C#, Vue.js,
  TypeScript and Azure technologies to build awesome products
baseurl: 
url: https://lord.technology
twitter_username: jme_lord
github_username: jamie-lord
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
show_excerpts: true
header_pages:
- projects.md
- blog.md
- work.md
- about.md
