---
title: Jamie Lord
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:name"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: false
    share: false
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
- scope:
    path: _projects
    type: projects
  values:
    layout: single
    author_profile: true
subtitle: Lord.technology
url: https://lord.technology
repository: jamie-lord/Lord.technology
email: jamie@lord.technology
description: Jamie Lord is CTO of HeadClear, based in Nottingham, UK using C#, GraphQL
  and Ionic Angular to build awesome products
github_username: jamie-lord
minimal_mistakes_skin: lord
search: true
locale: en-GB
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: "/:year/:month/:day/:title:output_ext"
paginate: 5
paginate_path: "/page:num/"
include:
- _pages
plugins:
- jekyll-remote-theme
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
- jekyll-seo-tag
author:
  name: Jamie Lord
  avatar: "/assets/images/jamie.jpg"
  bio: CTO using C#, GraphQL and Ionic Angular to build awesome products
  location: Nottingham, UK
  links:
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/jamie-lord
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://www.instagram.com/jlordlord
social:
  type: Person
  name: Jamie Lord
  links:
  - https://github.com/jamie-lord
footer:
  links:
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/jamie-lord
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://www.instagram.com/jlordlord
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  comments: all
  blanklines: true
  ignore:
    envs: development
analytics:
  provider: google-gtag
  google:
    tracking_id: G-SV12MR8FCS
